"""Backward-compatible facade for :mod:`biotools.structure`.

New code may import from the focused ``biotools.structure`` modules directly.
Existing imports from ``biotools.pdbtools`` remain supported.
"""

from .structure import (
    align_homologs,
    align_structure,
    apply_transformation,
    assign_secondary_structure,
    clip_chain,
    convert_cif_to_pdb,
    DSSPResidue,
    DSSPResult,
    extract_chain,
    get_aa_sequence,
    get_alignment,
    get_interaction_residues,
    get_interaction_residues_full,
    get_min_dist,
    get_pdb_metadata,
    get_pdb_structure,
    get_pdb_structure_as_mmcif,
    get_pdb_structure_as_pdb,
    get_residue_coords,
    get_rmsd,
    get_seqres_from_pdb,
    load_pdb_from_file,
    map_three_to_one,
    move_to_center,
    plot_structure,
    PDBMetadata,
    remove_wather_molecules,
    rename_chain,
    RCSBMetadataError,
    reset_index,
    save_structure_to_file,
    superimpose_PCA,
)
from .structure.alignment import _identify_homo_aa
from .structure.chains import (
    _get_chain,
    _get_protein_residues,
    _validate_chain_for_protein_alignment,
)
from .structure.io import _PDB_CHAIN_IDS, _resolve_pdb_chain_map

__all__ = [
    "align_homologs",
    "align_structure",
    "apply_transformation",
    "assign_secondary_structure",
    "clip_chain",
    "convert_cif_to_pdb",
    "DSSPResidue",
    "DSSPResult",
    "extract_chain",
    "get_aa_sequence",
    "get_alignment",
    "get_interaction_residues",
    "get_interaction_residues_full",
    "get_min_dist",
    "get_pdb_metadata",
    "get_pdb_structure",
    "get_pdb_structure_as_mmcif",
    "get_pdb_structure_as_pdb",
    "get_residue_coords",
    "get_rmsd",
    "get_seqres_from_pdb",
    "load_pdb_from_file",
    "map_three_to_one",
    "move_to_center",
    "plot_structure",
    "PDBMetadata",
    "remove_wather_molecules",
    "rename_chain",
    "RCSBMetadataError",
    "reset_index",
    "save_structure_to_file",
    "superimpose_PCA",
]
