[project]
name = "biotools"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopython>=1.86",
    "biotite>=1.5.0",
    "freesasa>=2.2.1",
    "matplotlib>=3.10.0",
    "numpy>=2.3.5",
    "pandas>=3.0.3",
    "py3dmol>=2.5.3",
    "pytest>=9.1.1",
]

[project.optional-dependencies]
contacts = [
    "openmm>=8.5.2",
]
md = [
    "openmm[cuda12]>=8.5.2",
    "pdbfixer>=1.12.0",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12"]
build-backend = "uv_build"
