"""Protein structure I/O, manipulation, alignment, and visualization."""

from .alignment import (
    align_homologs,
    align_structure,
    apply_transformation,
    get_alignment,
    get_rmsd,
)
from .chains import (
    clip_chain,
    extract_chain,
    get_aa_sequence,
    remove_wather_molecules,
    rename_chain,
    reset_index,
)
from .geometry import (
    characterize_chain_contacts,
    characterize_intrachain_contacts,
    DistanceMetric,
    get_interaction_residues,
    get_interaction_residues_full,
    get_min_dist,
    get_residue_coords,
    move_to_center,
    superimpose_PCA,
)
from .matrices import (
    DistanceMatrix,
    get_distance_matrix,
    get_interchain_distance_matrix,
    MatrixDistanceMetric,
)
from .io import (
    convert_cif_to_pdb,
    get_pdb_structure,
    get_pdb_structure_as_mmcif,
    get_pdb_structure_as_pdb,
    get_seqres_from_pdb,
    load_pdb_from_file,
    map_three_to_one,
    save_structure_to_file,
)
from .visualization import (
    InteractionMeasure,
    plot_distance_matrix,
    plot_interaction_matrix,
    plot_interchain_distance_matrix,
    plot_interchain_interaction_matrix,
    plot_structure,
)
from .metadata import PDBMetadata, RCSBMetadataError, get_pdb_metadata
from .secondary_structure import (
    AccessibilityScale,
    assign_secondary_structure,
    DSSPResidue,
    DSSPResult,
    ResidueID,
)
from .surface import (
    analyze_interaction_surface,
    calculate_sasa,
    InteractionSurfaceResult,
    InteractionSurfaceScore,
    ResidueInteractionSurfaceScore,
    SASAResidue,
    SASAResult,
)

__all__ = [
    "AccessibilityScale",
    "analyze_interaction_surface",
    "align_homologs",
    "align_structure",
    "apply_transformation",
    "assign_secondary_structure",
    "calculate_sasa",
    "characterize_chain_contacts",
    "characterize_intrachain_contacts",
    "clip_chain",
    "convert_cif_to_pdb",
    "DSSPResidue",
    "DSSPResult",
    "DistanceMetric",
    "DistanceMatrix",
    "extract_chain",
    "get_aa_sequence",
    "get_alignment",
    "get_distance_matrix",
    "get_interchain_distance_matrix",
    "get_interaction_residues",
    "get_interaction_residues_full",
    "get_min_dist",
    "get_pdb_structure",
    "get_pdb_structure_as_mmcif",
    "get_pdb_structure_as_pdb",
    "get_residue_coords",
    "get_rmsd",
    "get_seqres_from_pdb",
    "load_pdb_from_file",
    "InteractionSurfaceResult",
    "InteractionSurfaceScore",
    "InteractionMeasure",
    "map_three_to_one",
    "MatrixDistanceMetric",
    "move_to_center",
    "PDBMetadata",
    "plot_distance_matrix",
    "plot_interaction_matrix",
    "plot_interchain_distance_matrix",
    "plot_interchain_interaction_matrix",
    "plot_structure",
    "remove_wather_molecules",
    "rename_chain",
    "ResidueInteractionSurfaceScore",
    "ResidueID",
    "RCSBMetadataError",
    "reset_index",
    "save_structure_to_file",
    "SASAResidue",
    "SASAResult",
    "superimpose_PCA",
    "get_pdb_metadata",
]
